openapi: 3.0.0
info:
  title: Fusion Stock Analyst API
  description: AI-enhanced stock analysis platform with real-time signals and KPIs
  version: 1.7.4
  contact:
    name: Fusion Stock Analyst
    email: support@fusionanalyst.com

servers:
  - url: http://0.0.0.0:5000
    description: Development server

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"

  /api/fusion/dashboard:
    get:
      summary: Get fusion dashboard data
      parameters:
        - name: forceRefresh
          in: query
          schema:
            type: boolean
        - name: tf
          in: query
          schema:
            type: string
            enum: [All, 3D, 5D, 10D, 15D, 30D]
      responses:
        '200':
          description: Dashboard data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardData'

  /api/equities/list:
    get:
      summary: Get equities list
      responses:
        '200':
          description: List of equity items
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array

  /api/equities/kpis:
    get:
      summary: Get equity KPIs
      parameters:
        - name: timeframe
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Equity KPIs

  /api/options/strangle/candidates:
    get:
      summary: Get options strangle candidates
      parameters:
        - name: underlying
          in: query
          schema:
            type: string
            example: "TCS"
        - name: expiry
          in: query
          schema:
            type: string
            format: date
            example: "2025-08-28"
      responses:
        '200':
          description: Strangle candidates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    payoff:
                      type: number
                    margin:
                      type: number

  /api/commodities/signals:
    get:
      summary: Get commodity signals
      responses:
        '200':
          description: Commodity signals list

  /api/commodities/correlations:
    get:
      summary: Get commodity correlations
      parameters:
        - name: symbol
          in: query
          schema:
            type: string
            example: "GOLD"
      responses:
        '200':
          description: Correlation data

  /api/pins:
    get:
      summary: Get pinned items
      responses:
        '200':
          description: Pinned items
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
    post:
      summary: Update pinned items
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
      responses:
        '200':
          description: Success

  /api/locks:
    get:
      summary: Get locked items
      responses:
        '200':
          description: Locked items
    post:
      summary: Update locked items
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
      responses:
        '200':
          description: Success

  /api/kpi/metrics:
    get:
      summary: Get KPI metrics
      parameters:
        - name: timeframe
          in: query
          schema:
            type: string
            enum: [All, 3D, 5D, 10D, 15D, 30D]
            default: All
      responses:
        '200':
          description: KPI metrics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KPIMetrics'

  /docs:
    get:
      summary: Swagger UI Documentation
      description: Interactive API documentation using Swagger UI
      responses:
        '200':
          description: Swagger UI HTML page
          content:
            text/html:
              schema:
                type: string

components:
  schemas:
    Error:
      type: object
      required:
        - success
        - error
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "not_found"
        message:
          type: string
          example: "Resource not found"

    KPIMetrics:
      type: object
      properties:
        timeframe:
          type: string
          example: "30D"
        prediction_accuracy:
          type: number
          format: float
          example: 0.72
        sharpe_ratio:
          type: number
          format: float
          example: 1.35
        sortino_ratio:
          type: number
          format: float
          example: 1.48
        max_drawdown:
          type: number
          format: float
          example: -0.08
        expectancy:
          type: number
          format: float
          example: 1.42
        coverage:
          type: number
          format: float
          example: 0.89
        last_updated:
          type: string
          format: date-time
          example: "2024-08-11T16:45:00Z"

    DashboardData:
      type: object
      properties:
        kpis:
          type: object
        timeframes:
          type: object
        top_signals:
          type: array
          items:
            $ref: '#/components/schemas/Signal'
        pinned_rollup:
          type: object
        alerts:
          type: array
          items:
            type: string
        insights:
          type: string

    Signal:
      type: object
      properties:
        symbol:
          type: string
          example: "TCS"
        product:
          type: string
          example: "Equity"
        signal_score:
          type: number
          format: float
          example: 8.7
        current_price:
          type: number
          format: float
          example: 4275.30
        target_price:
          type: number
          format: float
          example: 4500.00
        potential_roi:
          type: number
          format: float
          example: 0.0526
        ai_verdict:
          type: string
          enum: [STRONG_BUY, BUY, HOLD, CAUTIOUS, AVOID]
          example: "STRONG_BUY"
        confidence:
          type: number
          format: float
          example: 0.87

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'