openapi: 3.0.0
info:
  title: Fusion Stock Analyst API
  description: AI-enhanced stock analysis platform with real-time signals and KPIs
  version: 1.7.4
  contact:
    name: Fusion Stock Analyst
    email: support@fusionanalyst.com

servers:
  - url: http://0.0.0.0:5000
    description: Development server

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"

  /api/fusion/dashboard:
    get:
      summary: Get fusion dashboard data
      parameters:
        - name: forceRefresh
          in: query
          schema:
            type: boolean
        - name: tf
          in: query
          schema:
            type: string
            enum: [All, 3D, 5D, 10D, 15D, 30D]
      responses:
        '200':
          description: Dashboard data
          content:
            application/json:
              schema:
                type: object
                properties:
                  kpis:
                    type: object
                  timeframes:
                    type: object
                  top_signals:
                    type: array
                  pinned_rollup:
                    type: object

  /api/equities/list:
    get:
      summary: Get equities list
      responses:
        '200':
          description: List of equity items
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array

  /api/equities/kpis:
    get:
      summary: Get equity KPIs
      parameters:
        - name: timeframe
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Equity KPIs

  /api/options/strangle/candidates:
    get:
      summary: Get options strangle candidates
      parameters:
        - name: underlying
          in: query
          schema:
            type: string
            example: "TCS"
        - name: expiry
          in: query
          schema:
            type: string
            format: date
            example: "2025-08-28"
      responses:
        '200':
          description: Strangle candidates
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    payoff:
                      type: number
                    margin:
                      type: number

  /api/commodities/signals:
    get:
      summary: Get commodity signals
      responses:
        '200':
          description: Commodity signals list

  /api/commodities/correlations:
    get:
      summary: Get commodity correlations
      parameters:
        - name: symbol
          in: query
          schema:
            type: string
            example: "GOLD"
      responses:
        '200':
          description: Correlation data

  /api/pins:
    get:
      summary: Get pinned items
      responses:
        '200':
          description: Pinned items
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
    post:
      summary: Update pinned items
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
      responses:
        '200':
          description: Success

  /api/locks:
    get:
      summary: Get locked items
      responses:
        '200':
          description: Locked items
    post:
      summary: Update locked items
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
      responses:
        '200':
          description: Success

  /api/kpi/metrics:
    get:
      summary: Get KPI metrics
      parameters:
        - name: timeframe
          in: query
          schema:
            type: string
      responses:
        '200':
          description: KPI metrics

components:
  schemas:
    Signal:
      type: object
      properties:
        symbol:
          type: string
        signal_score:
          type: number
        ai_verdict:
          type: string
        confidence:
          type: number